// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDrives():Promise<Array<main.DiskInfo>>;

export function GetStandardFilePaths():Promise<main.QuickPaths>;

export function ReadDirectory(arg1:string):Promise<main.DirResponse>;
