// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetStandardFilePaths() {
  return window['go']['main']['App']['GetStandardFilePaths']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}
